export const supportedLanguages = ["en", "vi"] as const;
export type Language = (typeof supportedLanguages)[number];
export const defaultLanguage: Language = "vi";

const en = {
  common: { events: "Events", login: "Login", logout: "Logout", admin: "Admin", organizer: "Organizer", language: "Language", email: "Email", password: "Password", phone: "Phone", save: "Save", cancel: "Cancel", status: "Status", actions: "Actions", loading: "Loading...", noDescription: "No description.", active: "Active", locked: "Locked" },
  header: { events: "Events", admin: "Admin", organizer: "Organizer", login: "Login", logout: "Logout" },
  home: { eyebrow: "EVENT PLATFORM", title: "Create. Review. Publish.", description: "Ticket Box centralizes organizer management and admin-approved events.", explore: "Explore events", workflow: "Workflow", workflowDescription: "An organizer creates a draft, submits it for review, and an admin publishes it." },
  login: { title: "Sign in", submit: "Sign in" },
  events: { eyebrow: "DISCOVER", title: "Events", loading: "Loading events...", empty: "No events to display.", submitReview: "Submit for review", approve: "Approve" },
  organizerPage: { title: "Organizer", notAssigned: "You have not been assigned to an organizer. Please contact an administrator.", createFor: "Create event for", createDraft: "Create draft", createSuccess: "Event created successfully.", createError: "Unable to create event.", eventList: "Organizer events", loading: "Loading events...", empty: "No events yet.", event: "Event", venue: "Venue", start: "Start", capacity: "Capacity", status: "Status", titleField: "Title", descriptionField: "Description", venueField: "Venue", startField: "Start time", endField: "End time" },
  adminLayout: { overview: "Overview", users: "User management", organizers: "Organizer management", events: "Event management", area: "Admin area", description: "Manage all Ticket Box data.", navigation: "Admin navigation" },
  dashboard: { eyebrow: "Workspace", title: "Admin dashboard", welcome: "Welcome to the Ticket Box admin area.", users: "Users", usersDescription: "Manage accounts and access permissions.", organizers: "Organizers", organizersDescription: "Manage event organizing units.", events: "Events", eventsDescription: "Track, create, and approve events." },
  adminEvents: { title: "Event management", add: "Add event", list: "Event list", loading: "Loading events...", empty: "No events yet.", event: "Event", venue: "Venue", start: "Start", capacity: "Capacity", status: "Status", actions: "Actions", approve: "Approve", none: "None", addNew: "Add new event", organizerId: "Organizer ID", eventTitle: "Title", description: "Description", end: "End", createSuccess: "Event created successfully.", createError: "Unable to create event." },
  adminUsers: { title: "User management", addUser: "Add user", userList: "User list", loading: "Loading user list...", empty: "No users yet.", noName: "No name yet", noPhone: "No phone number", fullName: "Full name", email: "Email", phone: "Phone", role: "Role", status: "Status", assignOrganizer: "Assign organizer", organizerId: "Organizer ID", assign: "Assign", cancel: "Cancel", save: "Save", addNewUser: "Add new user", password: "Password", userCreated: "New user created successfully.", createUserFailed: "Unable to create user.", assignedUser: "User assigned to organizer successfully.", assignFailed: "Unable to assign organizer.", active: "Active", inactive: "Locked" },
  adminOrganizers: { title: "Organizer management", addOrganizer: "Add organizer", organizerList: "Organizer list", loading: "Loading organizers...", empty: "No organizers yet.", name: "Organizer name", email: "Email", phone: "Phone", slug: "Slug", status: "Status", actions: "Actions", edit: "Edit", noPhone: "No phone number", active: "Active", inactive: "Locked", updateSuccess: "Organizer updated successfully.", createSuccess: "Organizer created successfully.", saveError: "Unable to save organizer.", addNewOrganizer: "Add new organizer", editOrganizer: "Edit organizer", cancel: "Cancel", save: "Save" },
  eventStatuses: { EVENT_STATUS_DRAFT: "Draft", EVENT_STATUS_PENDING_APPROVAL: "Pending approval", EVENT_STATUS_PUBLISHED: "Published", EVENT_STATUS_CANCELLED: "Cancelled", EVENT_STATUS_CLOSED: "Closed" },
  protectedRoute: { authenticating: "Authenticating..." },
} as const;

const vi = {
  common: { events: "Sự kiện", login: "Đăng nhập", logout: "Đăng xuất", admin: "Quản trị", organizer: "Tổ chức", language: "Ngôn ngữ", email: "Email", password: "Mật khẩu", phone: "Số điện thoại", save: "Lưu", cancel: "Huỷ", status: "Trạng thái", actions: "Thao tác", loading: "Đang tải...", noDescription: "Không có mô tả.", active: "Đang hoạt động", locked: "Đã khóa" },
  header: { events: "Sự kiện", admin: "Quản trị", organizer: "Tổ chức", login: "Đăng nhập", logout: "Đăng xuất" },
  home: { eyebrow: "NỀN TẢNG SỰ KIỆN", title: "Tạo. Duyệt. Xuất bản.", description: "Ticket Box tập trung quản lý đơn vị tổ chức và các sự kiện được quản trị viên phê duyệt.", explore: "Khám phá sự kiện", workflow: "Quy trình", workflowDescription: "Đơn vị tổ chức tạo bản nháp, gửi duyệt và quản trị viên xuất bản sự kiện." },
  login: { title: "Đăng nhập", submit: "Đăng nhập" },
  events: { eyebrow: "KHÁM PHÁ", title: "Sự kiện", loading: "Đang tải sự kiện...", empty: "Chưa có sự kiện nào để hiển thị.", submitReview: "Gửi duyệt", approve: "Duyệt" },
  organizerPage: { title: "Đơn vị tổ chức", notAssigned: "Bạn chưa được gán vào đơn vị tổ chức nào. Vui lòng liên hệ quản trị viên.", createFor: "Tạo sự kiện cho", createDraft: "Tạo bản nháp", createSuccess: "Tạo sự kiện thành công.", createError: "Không thể tạo sự kiện.", eventList: "Sự kiện của đơn vị tổ chức", loading: "Đang tải sự kiện...", empty: "Chưa có sự kiện nào.", event: "Sự kiện", venue: "Địa điểm", start: "Bắt đầu", capacity: "Sức chứa", status: "Trạng thái", titleField: "Tiêu đề", descriptionField: "Mô tả", venueField: "Địa điểm", startField: "Thời gian bắt đầu", endField: "Thời gian kết thúc" },
  adminLayout: { overview: "Tổng quan", users: "Quản trị người dùng", organizers: "Quản trị tổ chức", events: "Quản trị sự kiện", area: "Khu vực quản trị", description: "Quản lý toàn bộ dữ liệu Ticket Box.", navigation: "Điều hướng quản trị" },
  dashboard: { eyebrow: "Không gian làm việc", title: "Tổng quan quản trị", welcome: "Chào mừng bạn đến khu vực quản trị Ticket Box.", users: "Người dùng", usersDescription: "Quản lý tài khoản và quyền truy cập.", organizers: "Đơn vị tổ chức", organizersDescription: "Quản lý các đơn vị tổ chức sự kiện.", events: "Sự kiện", eventsDescription: "Theo dõi, tạo và duyệt sự kiện." },
  adminEvents: { title: "Quản trị sự kiện", add: "Thêm sự kiện", list: "Danh sách sự kiện", loading: "Đang tải sự kiện...", empty: "Chưa có sự kiện nào.", event: "Sự kiện", venue: "Địa điểm", start: "Bắt đầu", capacity: "Sức chứa", status: "Trạng thái", actions: "Thao tác", approve: "Duyệt", none: "Không có", addNew: "Thêm sự kiện mới", organizerId: "ID đơn vị tổ chức", eventTitle: "Tiêu đề", description: "Mô tả", end: "Kết thúc", createSuccess: "Tạo sự kiện thành công.", createError: "Không thể tạo sự kiện." },
  adminUsers: { title: "Quản trị người dùng", addUser: "Thêm người dùng", userList: "Danh sách người dùng", loading: "Đang tải danh sách người dùng...", empty: "Chưa có người dùng nào.", noName: "Chưa có họ tên", noPhone: "Không có số điện thoại", fullName: "Họ tên", email: "Email", phone: "Số điện thoại", role: "Vai trò", status: "Trạng thái", assignOrganizer: "Gán đơn vị tổ chức", organizerId: "ID đơn vị tổ chức", assign: "Gán", cancel: "Huỷ", save: "Lưu", addNewUser: "Thêm người dùng mới", password: "Mật khẩu", userCreated: "Tạo người dùng mới thành công.", createUserFailed: "Không thể tạo người dùng.", assignedUser: "Đã gán người dùng vào đơn vị tổ chức.", assignFailed: "Không thể gán đơn vị tổ chức.", active: "Đang hoạt động", inactive: "Đã khóa" },
  adminOrganizers: { title: "Quản trị tổ chức", addOrganizer: "Thêm tổ chức", organizerList: "Danh sách tổ chức", loading: "Đang tải tổ chức...", empty: "Chưa có tổ chức nào.", name: "Tên tổ chức", email: "Email", phone: "Số điện thoại", slug: "Slug", status: "Trạng thái", actions: "Thao tác", edit: "Sửa", noPhone: "Không có số điện thoại", active: "Đang hoạt động", inactive: "Đã khóa", updateSuccess: "Cập nhật tổ chức thành công.", createSuccess: "Tạo tổ chức thành công.", saveError: "Không thể lưu tổ chức.", addNewOrganizer: "Thêm tổ chức mới", editOrganizer: "Chỉnh sửa tổ chức", cancel: "Huỷ", save: "Lưu" },
  eventStatuses: { EVENT_STATUS_DRAFT: "Bản nháp", EVENT_STATUS_PENDING_APPROVAL: "Chờ phê duyệt", EVENT_STATUS_PUBLISHED: "Đã xuất bản", EVENT_STATUS_CANCELLED: "Đã huỷ", EVENT_STATUS_CLOSED: "Đã đóng" },
  protectedRoute: { authenticating: "Đang xác thực..." },
};

export const translations = { en, vi } as const;
export function getTranslations(language: Language) { return translations[language]; }
export function getText(language: Language, key: keyof typeof en.common) { return translations[language].common[key]; }
export function getEventStatusText(language: Language, status: keyof typeof en.eventStatuses) {
  return translations[language].eventStatuses[status];
}
